<?php

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    public function run()
    {
        $countries = [
            [
                'id' => 1,
                'name' => 'Afghanistan',
                'short_code' => 'af',
                'currency' => 'AFN',
            ],
            [
                'id' => 2,
                'name' => 'Albania',
                'short_code' => 'al',
                'currency' => 'ALL',
                ],
            [
                'id' => 3,
                'name' => 'Algeria',
                'short_code' => 'dz',
                'currency' => 'DZD',
                ],
            [
                'id' => 4,
                'name' => 'American Samoa',
                'short_code' => 'as',
                'currency' => 'USD',
                ],
            [
                'id' => 5,
                'name' => 'Andorra',
                'short_code' => 'ad',
                'currency' => 'EUR',
                ],
            [
                'id' => 6,
                'name' => 'Angola',
                'short_code' => 'ao',
                'currency' => 'AOA',
                ],
            [
                'id' => 7,
                'name' => 'Anguilla',
                'short_code' => 'ai',
                'currency' => 'XCD',
                ],
            [
                'id' => 8,
                'name' => 'Antarctica',
                'short_code' => 'aq',
                'currency' => 'ARS',
                ],
            [
                'id' => 9,
                'name' => 'Antigua and Barbuda',
                'short_code' => 'ag',
                'currency' => 'XCD',
                ],
            [
                'id' => 10,
                'name' => 'Argentina',
                'short_code' => 'ar',
                'currency' => 'ARS',
                ],
            [
                'id' => 11,
                'name' => 'Armenia',
                'short_code' => 'am',
                'currency' => 'AMD',
                ],
            [
                'id' => 12,
                'name' => 'Aruba',
                'short_code' => 'aw',
                'currency' => 'AWG',
                ],
            [
                'id' => 13,
                'name' => 'Australia',
                'short_code' => 'au',
                'currency' => 'AUD',
                ],
            [
                'id' => 14,
                'name' => 'Austria',
                'short_code' => 'at',

                'currency' => 'EUR',],
            [
                'id' => 15,
                'name' => 'Azerbaijan',
                'short_code' => 'az',
                'currency' => 'AZN',
                ],
            [
                'id' => 16,
                'name' => 'Bahamas',
                'short_code' => 'bs',
                'currency' => 'BSD',
                ],
            [
                'id' => 17,
                'name' => 'Bahrain',
                'short_code' => 'bh',
                'currency' => 'BHD',
                ],
            [
                'id' => 18,
                'name' => 'Bangladesh',
                'short_code' => 'bd',
                'currency' => 'BDT',
                ],
            [
                'id' => 19,
                'name' => 'Barbados',
                'short_code' => 'bb',
                'currency' => 'BBD',
                ],
            [
                'id' => 20,
                'name' => 'Belarus',
                'short_code' => 'by',
                'currency' => 'BYN',
                ],
            [
                'id' => 21,
                'name' => 'Belgium',
                'short_code' => 'be',
                'currency' => 'EUR',
                ],
            [
                'id' => 22,
                'name' => 'Belize',
                'short_code' => 'bz',
                'currency' => 'BZD',
                ],
            [
                'id' => 23,
                'name' => 'Benin',
                'short_code' => 'bj',
                'currency' => 'XOF',
                ],
            [
                'id' => 24,
                'name' => 'Bermuda',
                'short_code' => 'bm',
                'currency' => 'BMD',
                ],
            [
                'id' => 25,
                'name' => 'Bhutan',
                'short_code' => 'bt',
                'currency' => 'BTN',
                ],
            [
                'id' => 26,
                'name' => 'Bolivia',
                'short_code' => 'bo',
                'currency' => 'BOB',
                ],
            [
                'id' => 27,
                'name' => 'Bosnia and Herzegovina',
                'short_code' => 'ba',
                'currency' => 'BAM',
                ],
            [
                'id' => 28,
                'name' => 'Botswana',
                'short_code' => 'bw',
                'currency' => 'BWP',
                ],
            [
                'id' => 29,
                'name' => 'Brazil',
                'short_code' => 'br',
                'currency' => 'BRL',
                ],
            [
                'id' => 30,
                'name' => 'British Indian Ocean Territory',
                'short_code' => 'io',
                'currency' => 'USD',
                ],
            [
                'id' => 31,
                'name' => 'British Virgin Islands',
                'short_code' => 'vg',
                'currency' => 'USD',
                ],
            [
                'id' => 32,
                'name' => 'Brunei',
                'short_code' => 'bn',
                'currency' => 'BND',
                ],
            [
                'id' => 33,
                'name' => 'Bulgaria',
                'short_code' => 'bg',
                'currency' => 'BGN',
                ],
            [
                'id' => 34,
                'name' => 'Burkina Faso',
                'short_code' => 'bf',
                'currency' => 'XOF',
                ],
            [
                'id' => 35,
                'name' => 'Burundi',
                'short_code' => 'bi',
                'currency' => 'BIF',
                ],
            [
                'id' => 36,
                'name' => 'Cambodia',
                'short_code' => 'kh',
                'currency' => '',
            ],
            [
                'id' => 37,
                'name' => 'Cameroon',
                'short_code' => 'cm',
                'currency' => 'KHR',
                ],
            [
                'id' => 38,
                'name' => 'Canada',
                'short_code' => 'ca',
                'currency' => 'CAD',
                ],
            [
                'id' => 39,
                'name' => 'Cape Verde',
                'short_code' => 'cv',
                'currency' => 'CVE',
                ],
            [
                'id' => 40,
                'name' => 'Cayman Islands',
                'short_code' => 'ky',
                'currency' => 'KYD',
                ],
            [
                'id' => 41,
                'name' => 'Central African Republic',
                'short_code' => 'cf',
                'currency' => 'XAF',
                ],
            [
                'id' => 42,
                'name' => 'Chad',
                'short_code' => 'td',
                'currency' => 'XAF',
                ],
            [
                'id' => 43,
                'name' => 'Chile',
                'short_code' => 'cl',
                'currency' => 'CLP',
            ],
            [
                'id' => 44,
                'name' => 'China',
                'short_code' => 'cn',
                'currency' => 'CYN',
                ],
            [
                'id' => 45,
                'name' => 'Christmas Island',
                'short_code' => 'cx',
                'currency' => 'AUD',
                ],
            [
                'id' => 46,
                'name' => 'Cocos Islands',
                'short_code' => 'cc',
                'currency' => 'AUD',
                ],
            [
                'id' => 47,
                'name' => 'Colombia',
                'short_code' => 'co',
                'currency' => 'COP',
                ],
            [
                'id' => 48,
                'name' => 'Comoros',
                'short_code' => 'km',
                'currency' => 'KMF',
            ],
            [
                'id' => 49,
                'name' => 'Cook Islands',
                'short_code' => 'ck',
                'currency' => '',
                ],
            [
                'id' => 50,
                'name' => 'Costa Rica',
                'short_code' => 'cr',
                'currency' => '',
                ],
            [
                'id' => 51,
                'name' => 'Croatia',
                'short_code' => 'hr',
                'currency' => '',
                ],
            [
                'id' => 52,
                'name' => 'Cuba',
                'short_code' => 'cu',
                'currency' => '',
                ],
            [
                'id' => 53,
                'name' => 'Curacao',
                'short_code' => 'cw',
                'currency' => '',
                ],
            [
                'id' => 54,
                'name' => 'Cyprus',
                'short_code' => 'cy',
                'currency' => '',
                ],
            [
                'id' => 55,
                'name' => 'Czech Republic',
                'short_code' => 'cz',
                'currency' => '',
                ],
            [
                'id' => 56,
                'name' => 'Democratic Republic of the Congo',
                'short_code' => 'cd',
                'currency' => '',
                ],
            [
                'id' => 57,
                'name' => 'Denmark',
                'short_code' => 'dk',
                'currency' => 'DKK',
                ],
            [
                'id' => 58,
                'name' => 'Djibouti',
                'short_code' => 'dj',
                'currency' => 'DJF',
                ],
            [
                'id' => 59,
                'name' => 'Dominica',
                'short_code' => 'dm',
                'currency' => 'XCD',
                ],
            [
                'id' => 60,
                'name' => 'Dominican Republic',
                'short_code' => 'do',
                'currency' => 'DOP',
                ],
            [
                'id' => 61,
                'name' => 'East Timor',
                'short_code' => 'tl',
                'currency' => '',
                ],
            [
                'id' => 62,
                'name' => 'Ecuador',
                'short_code' => 'ec',
                'currency' => 'USD',
                ],
            [
                'id' => 63,
                'name' => 'Egypt',
                'short_code' => 'eg',
                'currency' => 'EGP',
                ],
            [
                'id' => 64,
                'name' => 'El Salvador',
                'short_code' => 'sv',
                'currency' => 'USD',
                ],
            [
                'id' => 65,
                'name' => 'Equatorial Guinea',
                'short_code' => 'gq',
                'currency' => 'XAF',
                ],
            [
                'id' => 66,
                'name' => 'Eritrea',
                'short_code' => 'er',
                'currency' => 'ERN',
                ],
            [
                'id' => 67,
                'name' => 'Estonia',
                'short_code' => 'ee',
                'currency' => 'EUR',
                ],
            [
                'id' => 68,
                'name' => 'Ethiopia',
                'short_code' => 'et',
                'currency' => 'ETP',
                ],
            [
                'id' => 69,
                'name' => 'Falkland Islands',
                'short_code' => 'fk',
                'currency' => '',
                ],
            [
                'id' => 70,
                'name' => 'Faroe Islands',
                'short_code' => 'fo',
                'currency' => 'FKP',
                ],
            [
                'id' => 71,
                'name' => 'Fiji',
                'short_code' => 'fj',
                'currency' => 'DKK',
                ],
            [
                'id' => 72,
                'name' => 'Finland',
                'short_code' => 'fi',
                'currency' => 'EUR',
                ],
            [
                'id' => 73,
                'name' => 'France',
                'short_code' => 'fr',
                'currency' => 'EUR',
                ],
            [
                'id' => 74,
                'name' => 'French Polynesia',
                'short_code' => 'pf',
                'currency' => 'XPF',
                ],
            [
                'id' => 75,
                'name' => 'Gabon',
                'short_code' => 'ga',
                'currency' => 'XAF',
                ],
            [
                'id' => 76,
                'name' => 'Gambia',
                'short_code' => 'gm',
                'currency' => 'GMD',
                ],
            [
                'id' => 77,
                'name' => 'Georgia',
                'short_code' => 'ge',
                'currency' => 'GEL',
                ],
            [
                'id' => 78,
                'name' => 'Germany',
                'short_code' => 'de',
                'currency' => 'EUR',
                ],
            [
                'id' => 79,
                'name' => 'Ghana',
                'short_code' => 'gh',
                'currency' => 'GHS',
                ],
            [
                'id' => 80,
                'name' => 'Gibraltar',
                'short_code' => 'gi',
                'currency' => 'GIP',
                ],
            [
                'id' => 81,
                'name' => 'Greece',
                'short_code' => 'gr',
                'currency' => 'EUR',
                ],
            [
                'id' => 82,
                'name' => 'Greenland',
                'short_code' => 'gl',
                'currency' => 'DKK',
                ],
            [
                'id' => 83,
                'name' => 'Grenada',
                'short_code' => 'gd',
                'currency' => 'XCD',
                ],
            [
                'id' => 84,
                'name' => 'Guam',
                'short_code' => 'gu',
                'currency' => 'USD',
                ],
            [
                'id' => 85,
                'name' => 'Guatemala',
                'short_code' => 'gt',
                'currency' => 'GTQ',
                ],
            [
                'id' => 86,
                'name' => 'Guernsey',
                'short_code' => 'gg',
                'currency' => 'GBP',
                ],
            [
                'id' => 87,
                'name' => 'Guinea',
                'short_code' => 'gn',
                'currency' => 'GNF',
                ],
            [
                'id' => 88,
                'name' => 'Guinea-Bissau',
                'short_code' => 'gw',
                'currency' => 'XOF',
                ],
            [
                'id' => 89,
                'name' => 'Guyana',
                'short_code' => 'gy',
                'currency' => '',
                ],
            [
                'id' => 90,
                'name' => 'Haiti',
                'short_code' => 'ht',
                'currency' => 'GYD',
                ],
            [
                'id' => 91,
                'name' => 'Honduras',
                'short_code' => 'hn',
                'currency' => 'HNL',
                ],
            [
                'id' => 92,
                'name' => 'Hong Kong',
                'short_code' => 'hk',
                'currency' => 'HKD',
                ],
            [
                'id' => 93,
                'name' => 'Hungary',
                'short_code' => 'hu',
                'currency' => 'HUF',
                ],
            [
                'id' => 94,
                'name' => 'Iceland',
                'short_code' => 'is',
                'currency' => 'ISK',
                ],
            [
                'id' => 95,
                'name' => 'India',
                'short_code' => 'in',
                'currency' => 'INR',
                ],
            [
                'id' => 96,
                'name' => 'Indonesia',
                'short_code' => 'id',
                'currency' => 'IDR',
                ],
            [
                'id' => 97,
                'name' => 'Iran',
                'short_code' => 'ir',
                'currency' => 'IRR',
                ],
            [
                'id' => 98,
                'name' => 'Iraq',
                'short_code' => 'iq',
                'currency' => 'IQD',
                ],
            [
                'id' => 99,
                'name' => 'Ireland',
                'short_code' => 'ie',
                'currency' => 'EUR',
                ],
            [
                'id' => 100,
                'name' => 'Isle of Man',
                'short_code' => 'im',
                'currency' => 'BP',
                ],
            [
                'id' => 102,
                'name' => 'Italy',
                'short_code' => 'it',
                'currency' => 'EUR',
                ],
            [
                'id' => 103,
                'name' => 'Ivory Coast',
                'short_code' => 'ci',
                'currency' => 'XOF',
                ],
            [
                'id' => 104,
                'name' => 'Jamaica',
                'short_code' => 'jm',
                'currency' => 'JMD',
                ],
            [
                'id' => 105,
                'name' => 'Japan',
                'short_code' => 'jp',
                'currency' => 'JPY',
                ],
            [
                'id' => 106,
                'name' => 'Jersey',
                'short_code' => 'je',
                'currency' => 'JBP',
                ],
            [
                'id' => 107,
                'name' => 'Jordan',
                'short_code' => 'jo',
                'currency' => 'JOD',
                ],
            [
                'id' => 108,
                'name' => 'Kazakhstan',
                'short_code' => 'kz',
                'currency' => 'KZT',
                ],
            [
                'id' => 109,
                'name' => 'Kenya',
                'short_code' => 'ke',
                'currency' => 'KES',
                ],
            [
                'id' => 110,
                'name' => 'Kiribati',
                'short_code' => 'ki',
                'currency' => 'AUD',
                ],
            [
                'id' => 111,
                'name' => 'Kosovo',
                'short_code' => 'xk',
                'currency' => '',
                ],
            [
                'id' => 112,
                'name' => 'Kuwait',
                'short_code' => 'kw',
                'currency' => 'KWD',
                ],
            [
                'id' => 113,
                'name' => 'Kyrgyzstan',
                'short_code' => 'kg',
                'currency' => 'KGS',
                ],
            [
                'id' => 114,
                'name' => 'Laos',
                'short_code' => 'la',
                'currency' => '',
                ],
            [
                'id' => 115,
                'name' => 'Latvia',
                'short_code' => 'lv',
                'currency' => 'EUR',
                ],
            [
                'id' => 116,
                'name' => 'Lebanon',
                'short_code' => 'lb',
                'currency' => 'LBP',
                ],
            [
                'id' => 117,
                'name' => 'Lesotho',
                'short_code' => 'ls',
                'currency' => 'LSL',
                ],
            [
                'id' => 118,
                'name' => 'Liberia',
                'short_code' => 'lr',
                'currency' => 'LRD',
                ],
            [
                'id' => 119,
                'name' => 'Libya',
                'short_code' => 'ly',
                'currency' => 'LYD',
                ],
            [
                'id' => 120,
                'name' => 'Liechtenstein',
                'short_code' => 'li',
                'currency' => 'CHF',
                ],
            [
                'id' => 121,
                'name' => 'Lithuania',
                'short_code' => 'lt',
                'currency' => 'EUR',
                ],
            [
                'id' => 122,
                'name' => 'Luxembourg',
                'short_code' => 'lu',
                'currency' => 'EUR',
                ],
            [
                'id' => 123,
                'name' => 'Macau',
                'short_code' => 'mo',
                'currency' => 'MOP',
                ],
            [
                'id' => 124,
                'name' => 'North Macedonia',
                'short_code' => 'mk',
                'currency' => 'MKD',
                ],
            [
                'id' => 125,
                'name' => 'Madagascar',
                'short_code' => 'mg',
                'currency' => 'MGA',
                ],
            [
                'id' => 126,
                'name' => 'Malawi',
                'short_code' => 'mw',
                'currency' => 'MWK',
                ],
            [
                'id' => 127,
                'name' => 'Malaysia',
                'short_code' => 'my',
                'currency' => 'MYR',
                ],
            [
                'id' => 128,
                'name' => 'Maldives',
                'short_code' => 'mv',
                'currency' => 'MVR',
                ],
            [
                'id' => 129,
                'name' => 'Mali',
                'short_code' => 'ml',
                'currency' => 'XOF',
                ],
            [
                'id' => 130,
                'name' => 'Malta',
                'short_code' => 'mt',
                'currency' => 'EUR',
                ],
            [
                'id' => 131,
                'name' => 'Marshall Islands',
                'short_code' => 'mh',
                'currency' => 'USD',
                ],
            [
                'id' => 132,
                'name' => 'Mauritania',
                'short_code' => 'mr',
                'currency' => 'EUR',
                ],
            [
                'id' => 133,
                'name' => 'Mauritius',
                'short_code' => 'mu',
                'currency' => 'MUR',
                ],
            [
                'id' => 134,
                'name' => 'Mayotte',
                'short_code' => 'yt',
                'currency' => 'EUR',
                ],
            [
                'id' => 135,
                'name' => 'Mexico',
                'short_code' => 'mx',
                'currency' => 'MXN',
                ],
            [
                'id' => 136,
                'name' => 'Micronesia',
                'short_code' => 'fm',
                'currency' => 'USD',
                ],
            [
                'id' => 137,
                'name' => 'Moldova',
                'short_code' => 'md',
                'currency' => 'MDL',
                ],
            [
                'id' => 138,
                'name' => 'Monaco',
                'short_code' => 'mc',
                'currency' => 'EUR',
                ],
            [
                'id' => 139,
                'name' => 'Mongolia',
                'short_code' => 'mn',
                'currency' => 'MNT',
                ],
            [
                'id' => 140,
                'name' => 'Montenegro',
                'short_code' => 'me',
                'currency' => 'EUR',
                ],
            [
                'id' => 141,
                'name' => 'Montserrat',
                'short_code' => 'ms',
                'currency' => 'XCD',
                ],
            [
                'id' => 142,
                'name' => 'Morocco',
                'short_code' => 'ma',
                'currency' => 'MAD',
                ],
            [
                'id' => 143,
                'name' => 'Mozambique',
                'short_code' => 'mz',
                'currency' => 'MZN',
                ],
            [
                'id' => 144,
                'name' => 'Myanmar',
                'short_code' => 'mm',
                'currency' => 'MMK',
                ],
            [
                'id' => 145,
                'name' => 'Namibia',
                'short_code' => 'na',
                'currency' => 'NAD',
                ],
            [
                'id' => 146,
                'name' => 'Nauru',
                'short_code' => 'nr',
                'currency' => 'AUD',
                ],
            [
                'id' => 147,
                'name' => 'Nepal',
                'short_code' => 'np',
                'currency' => 'NPR',
                ],
            [
                'id' => 148,
                'name' => 'Netherlands',
                'short_code' => 'nl',
                'currency' => 'EUR',
                ],
            [
                'id' => 149,
                'name' => 'Netherlands Antilles',
                'short_code' => 'an',
                'currency' => 'EUR',
                ],
            [
                'id' => 150,
                'name' => 'New Caledonia',
                'short_code' => 'nc',
                'currency' => 'XEF',
                ],
            [
                'id' => 151,
                'name' => 'New Zealand',
                'short_code' => 'nz',
                'currency' => 'NZD',
                ],
            [
                'id' => 152,
                'name' => 'Nicaragua',
                'short_code' => 'ni',
                'currency' => 'NIO',
                ],
            [
                'id' => 153,
                'name' => 'Niger',
                'short_code' => 'ne',
                'currency' => 'XOF',
                ],
            [
                'id' => 154,
                'name' => 'Nigeria',
                'short_code' => 'ng',
                'currency' => 'NGN',
                ],
            [
                'id' => 155,
                'name' => 'Niue',
                'short_code' => 'nu',
                'currency' => 'NZD',
                ],
            [
                'id' => 156,
                'name' => 'North Korea',
                'short_code' => 'kp',
                'currency' => 'KPU',
                ],
            [
                'id' => 157,
                'name' => 'Northern Mariana Islands',
                'short_code' => 'mp',
                'currency' => 'USD',
                ],
            [
                'id' => 158,
                'name' => 'Norway',
                'short_code' => 'no',
                'currency' => 'NOK',
                ],
            [
                'id' => 159,
                'name' => 'Oman',
                'short_code' => 'om',
                'currency' => 'OMR',
                ],
            [
                'id' => 160,
                'name' => 'Pakistan',
                'short_code' => 'pk',
                'currency' => 'PKR',
                ],
            [
                'id' => 161,
                'name' => 'Palau',
                'short_code' => 'pw',
                'currency' => 'USD',
                ],
            [
                'id' => 162,
                'name' => 'Palestine',
                'short_code' => 'ps',
                'currency' => 'ISL',
                ],
            [
                'id' => 163,
                'name' => 'Panama',
                'short_code' => 'pa',
                'currency' => 'USD',
                ],
            [
                'id' => 164,
                'name' => 'Papua New Guinea',
                'short_code' => 'pg',
                'currency' => 'PGK',
                ],
            [
                'id' => 165,
                'name' => 'Paraguay',
                'short_code' => 'py',
                'currency' => 'PYG',
                ],
            [
                'id' => 166,
                'name' => 'Peru',
                'short_code' => 'pe',
                'currency' => 'PEN',
                ],
            [
                'id' => 167,
                'name' => 'Philippines',
                'short_code' => 'ph',
                'currency' => 'PHP',
                ],
            [
                'id' => 168,
                'name' => 'Pitcairn',
                'short_code' => 'pn',
                'currency' => 'NZD',
                ],
            [
                'id' => 169,
                'name' => 'Poland',
                'short_code' => 'pl',
                'currency' => 'PLN',
                ],
            [
                'id' => 170,
                'name' => 'Portugal',
                'short_code' => 'pt',
                'currency' => 'EUR',
                ],
            [
                'id' => 171,
                'name' => 'Puerto Rico',
                'short_code' => 'pr',
                'currency' => 'USD',
                ],
            [
                'id' => 172,
                'name' => 'Qatar',
                'short_code' => 'qa',
                'currency' => 'QAR',
                ],
            [
                'id' => 173,
                'name' => 'Republic of the Congo',
                'short_code' => 'cg',
                'currency' => 'EUR',
                ],
            [
                'id' => 174,
                'name' => 'Reunion',
                'short_code' => 're',
                'currency' => 'EUR',
                ],
            [
                'id' => 175,
                'name' => 'Romania',
                'short_code' => 'ro',
                'currency' => 'EUR',
                ],
            [
                'id' => 176,
                'name' => 'Russia',
                'short_code' => 'ru',
                'currency' => 'RUB',
                ],
            [
                'id' => 177,
                'name' => 'Rwanda',
                'short_code' => 'rw',
                'currency' => 'EUR',
                ],
            [
                'id' => 178,
                'name' => 'Saint Barthelemy',
                'short_code' => 'bl',
                'currency' => 'EUR',
                ],
            [
                'id' => 179,
                'name' => 'Saint Helena',
                'short_code' => 'sh',
                'currency' => 'USD',
                ],
            [
                'id' => 180,
                'name' => 'Saint Kitts and Nevis',
                'short_code' => 'kn',
                'currency' => 'SPH',
                ],
            [
                'id' => 181,
                'name' => 'Saint Lucia',
                'short_code' => 'lc',
                'currency' => 'XCD',
                ],
            [
                'id' => 182,
                'name' => 'Saint Martin',
                'short_code' => 'mf',
                'currency' => 'XCD',
                ],
            [
                'id' => 183,
                'name' => 'Saint Pierre and Miquelon',
                'short_code' => 'pm',
                'currency' => 'EUR',
                ],
            [
                'id' => 184,
                'name' => 'Saint Vincent and the Grenadines',
                'short_code' => 'vc',
                'currency' => 'EUR',
                ],
            [
                'id' => 185,
                'name' => 'Samoa',
                'short_code' => 'ws',
                'currency' => '',
                ],
            [
                'id' => 186,
                'name' => 'San Marino',
                'short_code' => 'sm',
                'currency' => 'WST',
                ],
            [
                'id' => 187,
                'name' => 'Sao Tome and Principe',
                'short_code' => 'st',
                'currency' => 'EUR',
                ],
            [
                'id' => 188,
                'name' => 'Saudi Arabia',
                'short_code' => 'sa',
                'currency' => 'SAR',
                ],
            [
                'id' => 189,
                'name' => 'Senegal',
                'short_code' => 'sn',
                'currency' => 'XOF',
                ],
            [
                'id' => 190,
                'name' => 'Serbia',
                'short_code' => 'rs',
                'currency' => 'RSD',
                ],
            [
                'id' => 191,
                'name' => 'Seychelles',
                'short_code' => 'sc',
                'currency' => 'SCR',
                ],
            [
                'id' => 192,
                'name' => 'Sierra Leone',
                'short_code' => 'sl',
                'currency' => 'SLL',
                ],
            [
                'id' => 193,
                'name' => 'Singapore',
                'short_code' => 'sg',
                'currency' => 'SGD',
                ],
            [
                'id' => 194,
                'name' => 'Sint Maarten',
                'short_code' => 'sx',
                'currency' => 'ANG',
                ],
            [
                'id' => 195,
                'name' => 'Slovakia',
                'short_code' => 'sk',
                'currency' => 'EUR',
                ],
            [
                'id' => 196,
                'name' => 'Slovenia',
                'short_code' => 'si',
                'currency' => 'EUR',
                ],
            [
                'id' => 197,
                'name' => 'Solomon Islands',
                'short_code' => 'sb',
                'currency' => 'EUR',
                ],
            [
                'id' => 198,
                'name' => 'Somalia',
                'short_code' => 'so',
                'currency' => 'EUR',
                ],
            [
                'id' => 199,
                'name' => 'South Africa',
                'short_code' => 'za',
                'currency' => 'ZAR',
                ],
            [
                'id' => 200,
                'name' => 'South Korea',
                'short_code' => 'kr',
                'currency' => 'KRW',
                ],
            [
                'id' => 201,
                'name' => 'South Sudan',
                'short_code' => 'ss',
                'currency' => 'SSP',
            ],
            [
                'id' => 202,
                'name' => 'Spain',
                'short_code' => 'es',
                'currency' => 'EUR',
                ],
            [
                'id' => 203,
                'name' => 'Sri Lanka',
                'short_code' => 'lk',
                'currency' => 'LKR',
                ],
            [
                'id' => 204,
                'name' => 'Sudan',
                'short_code' => 'sd',
                'currency' => 'SDG',
                ],
            [
                'id' => 205,
                'name' => 'Suriname',
                'short_code' => 'sr',
                'currency' => 'SRD',
                ],
            [
                'id' => 206,
                'name' => 'Svalbard and Jan Mayen',
                'short_code' => 'sj',
                'currency' => 'EUR',
                ],
            [
                'id' => 207,
                'name' => 'Swaziland',
                'short_code' => 'sz',
                'currency' => 'SZP',
                ],
            [
                'id' => 208,
                'name' => 'Sweden',
                'short_code' => 'se',
                'currency' => 'SEK',
            ],
            [
                'id' => 209,
                'name' => 'Switzerland',
                'short_code' => 'ch',
                'currency' => 'CHF',
                ],
            [
                'id' => 210,
                'name' => 'Syria',
                'short_code' => 'sy',
                'currency' => 'SYP',
                ],
            [
                'id' => 211,
                'name' => 'Taiwan',
                'short_code' => 'tw',
                'currency' => 'TWD',
                ],
            [
                'id' => 212,
                'name' => 'Tajikistan',
                'short_code' => 'tj',
                'currency' => 'TJS',
                ],
            [
                'id' => 213,
                'name' => 'Tanzania',
                'short_code' => 'tz',
                'currency' => 'TZS',
                ],
            [
                'id' => 214,
                'name' => 'Thailand',
                'short_code' => 'th',
                'currency' => 'THP',
                ],
            [
                'id' => 215,
                'name' => 'Togo',
                'short_code' => 'tg',
                'currency' => 'USD',
                ],
            [
                'id' => 216,
                'name' => 'Tokelau',
                'short_code' => 'tk',
                'currency' => 'USD',
                ],
            [
                'id' => 217,
                'name' => 'Tonga',
                'short_code' => 'to',
                'currency' => 'USD',
                ],
            [
                'id' => 218,
                'name' => 'Trinidad and Tobago',
                'short_code' => 'tt',
                'currency' => 'XOF',
                ],
            [
                'id' => 219,
                'name' => 'Tunisia',
                'short_code' => 'tn',
                'currency' => 'TND',
                ],
            [
                'id' => 220,
                'name' => 'Turkey',
                'short_code' => 'tr',
                'currency' => 'TRY',
                ],
            [
                'id' => 221,
                'name' => 'Turkmenistan',
                'short_code' => 'tm',
                'currency' => 'TMT',
                ],
            [
                'id' => 222,
                'name' => 'Turks and Caicos Islands',
                'short_code' => 'tc',
                'currency' => 'USD',
                ],
            [
                'id' => 223,
                'name' => 'Tuvalu',
                'short_code' => 'tv',
                'currency' => 'TSD',
                ],
            [
                'id' => 224,
                'name' => 'U.S. Virgin Islands',
                'short_code' => 'vi',
                'currency' => 'USD',
                ],
            [
                'id' => 225,
                'name' => 'Uganda',
                'short_code' => 'ug',
                'currency' => 'UGX',
                ],
            [
                'id' => 226,
                'name' => 'Ukraine',
                'short_code' => 'ua',
                'currency' => 'EUR',
                ],
            [
                'id' => 227,
                'name' => 'United Arab Emirates',
                'short_code' => 'ae',
                'currency' => 'AED',
                ],
            [
                'id' => 228,
                'name' => 'United Kingdom',
                'short_code' => 'gb',
                'currency' => 'GBP',
                ],
            [
                'id' => 229,
                'name' => 'United States',
                'short_code' => 'us',
                'currency' => 'USD',
                ],
            [
                'id' => 230,
                'name' => 'Uruguay',
                'short_code' => 'uy',
                'currency' => 'UYU',
                ],
            [
                'id' => 231,
                'name' => 'Uzbekistan',
                'short_code' => 'uz',
                'currency' => 'UZS',
                ],
            [
                'id' => 232,
                'name' => 'Vanuatu',
                'short_code' => 'vu',
                'currency' => 'VUP',
                ],
            [
                'id' => 233,
                'name' => 'Vatican',
                'short_code' => 'va',
                'currency' => 'XOF',
                ],
            [
                'id' => 234,
                'name' => 'Venezuela',
                'short_code' => 've',
                'currency' => '',
                ],
            [
                'id' => 235,
                'name' => 'Vietnam',
                'short_code' => 'vn',
                'currency' => 'XOF',
                ],
            [
                'id' => 236,
                'name' => 'Wallis and Futuna',
                'short_code' => 'wf',
                'currency' => 'WFP',
                ],
            [
                'id' => 237,
                'name' => 'Western Sahara',
                'short_code' => 'eh',
                'currency' => 'EHD',
                ],
            [
                'id' => 238,
                'name' => 'Yemen',
                'short_code' => 'ye',
                'currency' => 'YER',
                ],
            [
                'id' => 239,
                'name' => 'Zambia',
                'short_code' => 'zm',
                'currency' => 'ZMW',
    ],
            [
                'id' => 240,
                'name' => 'Zimbabwe',
                'short_code' => 'zw',
                'currency' => 'BWP',
                ],
        ];

        Country::insert($countries);
    }
}
